export const imagesConfig = {
  floral: [
    {
      src: "/images/floral/floral.jpg",
      original: "/images/floral/floral.jpg",
      width: 250,
      height: 330,
    },
    {
      src: "/images/floral/floral1.jpg",
      original: "/images/floral/floral1.jpg",
      width: 350,
      height: 332,
    },
    {
      src: "/images/floral/floral6.jpg",
      original: "/images/floral/floral6.jpg",
      width: 300,
      height: 312,
    },
    {
      src: "/images/floral/floral2.jpg",
      original: "/images/floral/floral2.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/floral/floral3.jpg",
      original: "/images/floral/floral3.jpg",
      width: 350,
      height: 332,
    },
    {
      src: "/images/floral/floral4.jpg",
      original: "/images/floral/floral4.jpg",
      width: 350,
      height: 332,
    },
    {
      src: "/images/floral/floral5.jpg",
      original: "/images/floral/floral5.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/floral/floral7.jpg",
      original: "/images/floral/floral7.jpg",
      width: 380,
      height: 352,
    },
    {
      src: "/images/floral/floral10.jpg",
      original: "/images/floral/floral10.jpg",
      width: 290,
      height: 340,
    },
    {
      src: "/images/floral/floral9.jpg",
      original: "/images/floral/floral9.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/floral/floral8.jpg",
      original: "/images/floral/floral8.jpg",
      width: 290,
      height: 340,
    },
    {
      src: "/images/floral/floral11.jpg",
      original: "/images/floral/floral11.jpg",
      width: 290,
      height: 340,
    },
    {
      src: "/images/floral/floral12.jpg",
      original: "/images/floral/floral12.jpg",
      width: 380,
      height: 312,
    },
    {
      src: "/images/floral/floral13.jpg",
      original: "/images/floral/floral13.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/floral/floral14.jpg",
      original: "/images/floral/floral14.jpg",
      width: 400,
      height: 280,
    },
    {
      src: "/images/floral/floral15.jpg",
      original: "/images/floral/floral15.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/floral/floral16.jpg",
      original: "/images/floral/floral16.jpg",
      width: 290,
      height: 340,
    },
    {
      src: "/images/floral/floral17.jpg",
      original: "/images/floral/floral17.jpg",
      width: 320,
      height: 183,
    },
    {
      src: "/images/floral/floral18.jpg",
      original: "/images/floral/floral18.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/floral/floral19.jpg",
      original: "/images/floral/floral19.jpg",
      width: 320,
      height: 212,
    },
    {
      src: "/images/floral/floral20.jpg",
      original: "/images/floral/floral20.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/floral/floral21.jpg",
      original: "/images/floral/floral21.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/floral/floral22.jpg",
      original: "/images/floral/floral22.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/floral/floral23.jpg",
      original: "/images/floral/floral23.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/floral/floral24.jpg",
      original: "/images/floral/floral24.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/floral/floral25.jpg",
      original: "/images/floral/floral25.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/floral/floral26.jpg",
      original: "/images/floral/floral26.jpg",

      width: 340,
      height: 332,
    },
    {
      src: "/images/floral/floral27.jpg",
      original: "/images/floral/floral27.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/floral/floral28.jpeg",
      original: "/images/floral/floral28.jpeg",

      width: 320,
      height: 312,
    },
    {
      src: "/images/floral/floral29.jpg",
      original: "/images/floral/floral29.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/floral/floral30.jpg",
      original: "/images/floral/floral30.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/floral/floral31.jpg",
      original: "/images/floral/floral31.jpg",

      width: 380,
      height: 340,
    },
    {
      src: "/images/floral/floral32.jpg",
      original: "/images/floral/floral32.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding11.jpg",
      original: "/images/wedding/wedding11.jpg",
      width: 320,
      height: 343,
    },
    {
      src: "/images/wedding/wedding12.jpeg",
      original: "/images/wedding/wedding12.jpeg",
      width: 290,
      height: 312,
    },
    {
      src: "/images/wedding/wedding14.jpg",
      original: "/images/wedding/wedding14.jpg",
      width: 320,
      height: 270,
    },
    {
      src: "/images/wedding/wedding16.jpg",
      original: "/images/wedding/wedding16.jpg",
      width: 420,
      height: 390,
    },
    {
      src: "/images/wedding/wedding18.jpg",
      original: "/images/wedding/wedding18.jpg",
      width: 340,
      height: 360,
    },
    {
      src: "/images/wedding/wedding20.jpg",
      original: "/images/wedding/wedding20.jpg",
      width: 320,
      height: 312,
    },
  ],
  wedding: [
    {
      src: "/images/wedding/wedding.jpg",
      original: "/images/wedding/wedding.jpg",
      width: 350,
      height: 330,
    },
    {
      src: "/images/wedding/wedding1.jpg",
      original: "/images/wedding/wedding1.jpg",
      width: 370,
      height: 320,
    },
    {
      src: "/images/wedding/wedding6.jpg",
      original: "/images/wedding/wedding6.jpg",
      width: 320,
      height: 250,
    },
    {
      src: "/images/wedding/wedding2.jpg",
      original: "/images/wedding/wedding2.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/wedding/wedding3.jpg",
      original: "/images/wedding/wedding3.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/wedding/wedding4.jpg",
      original: "/images/wedding/wedding4.jpg",
      width: 320,
      height: 283,
    },
    {
      src: "/images/wedding/wedding5.jpg",
      original: "/images/wedding/wedding5.jpg",
      width: 380,
      height: 270,
    },

    {
      src: "/images/wedding/wedding7.jpg",
      original: "/images/wedding/wedding7.jpg",
      width: 360,
      height: 312,
    },
    {
      src: "/images/wedding/wedding10.jpeg",
      original: "/images/wedding/wedding10.jpeg",
      width: 310,
      height: 340,
    },
    {
      src: "/images/wedding/wedding9.PNG",
      original: "/images/wedding/wedding9.PNG",
      alt: "Big Ben - London",
      width: 320,
      height: 390,
    },
    {
      src: "/images/wedding/wedding8.jpg",
      original: "/images/wedding/wedding8.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/wedding/wedding21.jpg",
      original: "/images/wedding/wedding21.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/wedding/wedding22.jpg",
      original: "/images/wedding/wedding22.jpg",

      width: 300,
      height: 320,
    },
    {
      src: "/images/wedding/wedding23.jpg",
      original: "/images/wedding/wedding23.jpg",
      width: 350,
      height: 303,
    },
    {
      src: "/images/wedding/wedding24.jpg",
      original: "/images/wedding/wedding24.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding25.jpg",
      original: "/images/wedding/wedding25.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/wedding/wedding26.jpg",
      original: "/images/wedding/wedding26.jpg",

      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding27.jpg",
      original: "/images/wedding/wedding27.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding28.jpg",
      original: "/images/wedding/wedding28.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/wedding/wedding29.jpg",
      original: "/images/wedding/wedding29.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding30.jpg",
      original: "/images/wedding/wedding30.jpg",
      width: 320,
      height: 313,
    },
    {
      src: "/images/wedding/wedding31.jpg",
      original: "/images/wedding/wedding31.jpg",

      width: 320,
      height: 300,
    },
    {
      src: "/images/wedding/wedding32.jpg",
      original: "/images/wedding/wedding32.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding33.jpg",
      original: "/images/wedding/wedding33.jpg",
      width: 420,
      height: 490,
    },
    {
      src: "/images/wedding/wedding34.jpg",
      original: "/images/wedding/wedding34.jpg",
      width: 520,
      height: 382,
    },
    {
      src: "/images/wedding/wedding35.jpg",
      original: "/images/wedding/wedding35.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding36.jpg",
      original: "/images/wedding/wedding36.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/wedding/wedding37.jpg",
      original: "/images/wedding/wedding37.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/wedding/wedding38.jpg",
      original: "/images/wedding/wedding38.jpg",
      width: 320,
      height: 183,
    },
    {
      src: "/images/wedding/wedding39.jpg",
      original: "/images/wedding/wedding39.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/wedding/wedding40.jpg",
      original: "/images/wedding/wedding40.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding41.jpg",
      original: "/images/wedding/wedding41.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/wedding/wedding42.jpg",
      original: "/images/wedding/wedding42.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/wedding/wedding43.jpg",
      original: "/images/wedding/wedding43.jpg",

      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding44.jpg",
      original: "/images/wedding/wedding44.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding45.jpg",
      original: "/images/wedding/wedding45.jpg",
      width: 320,
      height: 250,
    },
    {
      src: "/images/wedding/wedding46.jpg",
      original: "/images/wedding/wedding46.jpg",
      width: 420,
      height: 312,
    },
    {
      src: "/images/wedding/wedding47.jpg",
      original: "/images/wedding/wedding47.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding48.jpg",
      original: "/images/wedding/wedding48.jpg",
      width: 320,
      height: 352,
    },
    {
      src: "/images/wedding/wedding49.jpg",
      original: "/images/wedding/wedding49.jpg",
      width: 320,
      height: 352,
    },
    {
      src: "/images/wedding/wedding50.jpg",
      original: "/images/wedding/wedding50.jpg",
      width: 320,
      height: 280,
    },
    {
      src: "/images/wedding/wedding51.jpg",
      original: "/images/wedding/wedding51.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/wedding/wedding52.jpg",
      original: "/images/wedding/wedding52.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding53.jpg",
      original: "/images/wedding/wedding53.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/wedding/wedding54.jpg",
      original: "/images/wedding/wedding54.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/wedding/wedding55.jpg",
      original: "/images/wedding/wedding55.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/wedding/wedding56.jpg",
      original: "/images/wedding/wedding56.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding57.jpg",
      original: "/images/wedding/wedding57.jpg",
      width: 320,
      height: 310,
    },
    {
      src: "/images/wedding/wedding58.jpg",
      original: "/images/wedding/wedding58.jpg",
      alt: "Big Ben - London",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding59.jpg",
      original: "/images/wedding/wedding59.jpg",

      width: 320,
      height: 350,
    },
    {
      src: "/images/wedding/wedding60.jpg",
      original: "/images/wedding/wedding60.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding61.jpg",
      original: "/images/wedding/wedding61.jpg",

      width: 360,
      height: 400,
    },
    {
      src: "/images/wedding/wedding62.jpg",
      original: "/images/wedding/wedding62.jpg",
      width: 320,
      height: 320,
    },
    {
      src: "/images/wedding/wedding63.jpg",
      original: "/images/wedding/wedding63.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding64.jpg",
      original: "/images/wedding/wedding64.jpg",

      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding65.jpg",
      original: "/images/wedding/wedding65.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding66.jpg",
      original: "/images/wedding/wedding66.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/wedding/wedding67.jpg",
      original: "/images/wedding/wedding67.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/wedding/wedding68.jpg",
      original: "/images/wedding/wedding68.jpg",
      width: 320,
      height: 250,
    },
    {
      src: "/images/wedding/wedding69.jpg",
      original: "/images/wedding/wedding69.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/wedding/wedding70.jpg",
      original: "/images/wedding/wedding70.jpg",
      width: 320,
      height: 212,
    },
    {
      src: "/images/wedding/wedding71.jpg",
      original: "/images/wedding/wedding71.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding72.jpg",
      original: "/images/wedding/wedding72.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/wedding/wedding73.jpg",
      original: "/images/wedding/wedding73.jpg",

      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding74.jpg",
      original: "/images/wedding/wedding74.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding75.jpg",
      original: "/images/wedding/wedding75.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/wedding/wedding76.jpg",
      original: "/images/wedding/wedding76.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/wedding/wedding77.jpg",
      original: "/images/wedding/wedding77.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding78.jpg",
      original: "/images/wedding/wedding78.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding79.jpg",
      original: "/images/wedding/wedding79.jpg",

      width: 320,
      height: 312,
    },
    {
      src: "/images/wedding/wedding80.jpg",
      original: "/images/wedding/wedding80.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/wedding/wedding81.jpg",
      original: "/images/wedding/wedding81.jpg",
      width: 313,
      height: 320,
    },
  ],
  seasonal: [
    {
      src: "/images/seasonal/seasonal.jpg",
      original: "/images/seasonal/seasonal.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/seasonal/seasonal1.jpg",
      original: "/images/seasonal/seasonal1.jpg",
      width: 420,
      height: 312,
    },
    {
      src: "/images/seasonal/seasonal6.jpg",
      original: "/images/seasonal/seasonal6.jpg",
      width: 320,
      height: 190,
    },
    {
      src: "/images/seasonal/seasonal2.jpg",
      original: "/images/seasonal/seasonal2.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/seasonal/seasonal3.jpg",
      original: "/images/seasonal/seasonal3.jpg",
      width: 320,
      height: 352,
    },
    {
      src: "/images/seasonal/seasonal4.jpg",
      original: "/images/seasonal/seasonal4.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/seasonal/seasonal5.jpg",
      original: "/images/seasonal/seasonal5.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/seasonal/seasonal7.jpg",
      original: "/images/seasonal/seasonal7.jpg",
      width: 390,
      height: 312,
    },
    {
      src: "/images/seasonal/seasonal10.jpg",
      original: "/images/seasonal/seasonal10.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/seasonal/seasonal9.jpg",
      original: "/images/seasonal/seasonal9.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal8.jpg",
      original: "/images/seasonal/seasonal8.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/seasonal/seasonal11.jpg",
      original: "/images/seasonal/seasonal11.jpg",
      width: 270,
      height: 352,
    },
    {
      src: "/images/seasonal/seasonal12.jpg",
      original: "/images/seasonal/seasonal12.jpg",
      width: 390,
      height: 342,
    },
    {
      src: "/images/seasonal/seasonal13.jpg",
      original: "/images/seasonal/seasonal13.jpg",
      width: 420,
      height: 312,
    },
    {
      src: "/images/seasonal/seasonal14.jpg",
      original: "/images/seasonal/seasonal14.jpg",
      width: 400,
      height: 312,
    },
    {
      src: "/images/seasonal/seasonal15.jpg",
      original: "/images/seasonal/seasonal15.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/seasonal/seasonal16.jpg",
      original: "/images/seasonal/seasonal16.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/seasonal/seasonal17.jpg",
      original: "/images/seasonal/seasonal17.jpg",
      width: 370,
      height: 342,
    },
    {
      src: "/images/seasonal/seasonal18.jpg",
      original: "/images/seasonal/seasonal18.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/seasonal/seasonal19.jpg",
      original: "/images/seasonal/seasonal19.jpg",
      width: 420,
      height: 312,
    },
    {
      src: "/images/seasonal/seasonal20.jpg",
      original: "/images/seasonal/seasonal20.jpg",
      width: 320,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal21.jpg",
      original: "/images/seasonal/seasonal21.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal22.jpg",
      original: "/images/seasonal/seasonal22.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/seasonal/seasonal23.jpg",
      original: "/images/seasonal/seasonal23.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal24.jpg",
      original: "/images/seasonal/seasonal24.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/seasonal/seasonal25.jpg",
      original: "/images/seasonal/seasonal25.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal26.jpg",
      original: "/images/seasonal/seasonal26.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/seasonal/seasonal27.jpg",
      original: "/images/seasonal/seasonal27.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal28.jpg",
      original: "/images/seasonal/seasonal28.jpg",
      width: 320,
      height: 250,
    },
    {
      src: "/images/seasonal/seasonal29.jpg",
      original: "/images/seasonal/seasonal29.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal30.jpg",
      original: "/images/seasonal/seasonal30.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/seasonal/seasonal31.jpg",
      original: "/images/seasonal/seasonal31.jpg",
      width: 360,
      height: 332,
    },
  ],
  outdoor: [
    {
      src: "/images/outdoor/outdoor.jpg",
      original: "/images/outdoor/outdoor.jpg",
      width: 250,
      height: 312,
    },
    {
      src: "/images/outdoor/outdoo1.jpg",
      original: "/images/outdoor/outdoo1.jpg",
      width: 290,
      height: 312,
    },
    {
      src: "/images/outdoor/outdoo6.jpg",
      original: "/images/outdoor/outdoo6.jpg",
      width: 390,
      height: 372,
    },
    {
      src: "/images/outdoor/outdoo2.jpg",
      original: "/images/outdoor/outdoo2.jpg",
      width: 480,
      height: 462,
    },
    {
      src: "/images/outdoor/outdoo3.jpg",
      original: "/images/outdoor/outdoo3.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/outdoor/outdoo4.jpg",
      original: "/images/outdoor/outdoo4.jpg",
      width: 320,
      height: 193,
    },
    {
      src: "/images/outdoor/outdoo5.jpg",
      original: "/images/outdoor/outdoo5.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/outdoor/outdoo7.jpg",
      original: "/images/outdoor/outdoo7.jpg",
      width: 320,
      height: 212,
    },
    {
      src: "/images/outdoor/outdoo10.jpg",
      original: "/images/outdoor/outdoo10.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/outdoor/outdoo9.jpg",
      original: "/images/outdoor/outdoo9.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/outdoor/outdoo8.jpg",
      original: "/images/outdoor/outdoo8.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/outdoor/outdoo11.jpg",
      original: "/images/outdoor/outdoo11.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/outdoor/outdoo12.jpg",
      original: "/images/outdoor/outdoo12.jpg",
      width: 320,
      height: 174,
    },
    {
      src: "/images/outdoor/outdoo13.jpg",
      original: "/images/outdoor/outdoo13.jpg",
      width: 380,
      height: 312,
    },
    {
      src: "/images/outdoor/outdoo14.jpg",
      original: "/images/outdoor/outdoo14.jpg",
      width: 350,
      height: 300,
    },
    {
      src: "/images/outdoor/outdoo15.jpg",
      original: "/images/outdoor/outdoo15.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/outdoor/outdoo16.jpg",
      original: "/images/outdoor/outdoo16.jpg",
      width: 420,
      height: 352,
    },
    {
      src: "/images/outdoor/outdoo17.jpg",
      original: "/images/outdoor/outdoo17.jpg",
      width: 320,
      height: 183,
    },
    {
      src: "/images/outdoor/outdoo18.jpg",
      original: "/images/outdoor/outdoo18.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/outdoor/outdoo19.jpg",
      original: "/images/outdoor/outdoo19.jpg",
      width: 320,
      height: 312,
    },
    {
      src: "/images/outdoor/outdoo20.jpg",
      original: "/images/outdoor/outdoo20.jpg",
      width: 360,
      height: 300,
    },
    {
      src: "/images/outdoor/outdoo21.jpg",
      original: "/images/outdoor/outdoo21.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/outdoor/outdoo22.jpg",
      original: "/images/outdoor/outdoo22.jpg",

      width: 300,
      height: 312,
    },
    {
      src: "/images/outdoor/outdoo23.jpg",
      original: "/images/outdoor/outdoo23.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/outdoor/outdoo24.jpg",
      original: "/images/outdoor/outdoo24.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/outdoor/outdoo25.jpg",
      original: "/images/outdoor/outdoo25.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/outdoor/outdoo26.jpg",
      original: "/images/outdoor/outdoo26.jpg",

      width: 320,
      height: 312,
    },
    {
      src: "/images/outdoor/outdoo27.jpg",
      original: "/images/outdoor/outdoo27.jpg",
      width: 313,
      height: 320,
    },
    {
      src: "/images/outdoor/outdoo28.jpg",
      original: "/images/outdoor/outdoo28.jpg",

      width: 390,
      height: 372,
    },
    {
      src: "/images/outdoor/hero.jpg",
      original: "/images/outdoor/hero.jpg",
      width: 313,
      height: 320,
    },
  ],
  events: [
    {
      src: "/images/event/event.jpg",
      original: "/images/event/event.jpg",
      width: 320,
      height: 174,
    },
    {
      src: "/images/event/event1.PNG",
      original: "/images/event1/event.jpg",
      width: 520,
      height: 312,
    },
    {
      src: "/images/event/event6.jpg",
      original: "/images/event/event6.jpg",
      width: 320,
      height: 190,
    },
    {
      src: "/images/event/event2.jpg",
      original: "/images/event/event2.jpg",
      width: 392,
      height: 420,
    },
    {
      src: "/images/event/event3.jpg",
      original: "/images/event/event3.jpg",
      width: 352,
      height: 420,
    },
    {
      src: "/images/event/event4.jpg",
      original: "/images/event/event4.jpg",
      width: 320,
      height: 183,
    },
    {
      src: "/images/event/event5.jpg",
      original: "/images/event/event5.jpg",
      width: 240,
      height: 320,
    },

    {
      src: "/images/event/event7.jpg",
      original: "/images/event/event7.jpg",
      width: 420,
      height: 312,
    },
    {
      src: "/images/event/event10.jpg",
      original: "/images/event/event10.jpg",
      width: 320,
      height: 290,
    },
    {
      src: "/images/event/event9.jpg",
      original: "/images/event/event9.jpg",
      alt: "Big Ben - London",
      width: 248,
      height: 320,
    },
    {
      src: "/images/event/event8.jpg",
      original: "/images/event/event8.jpg",

      width: 320,
      height: 250,
    },
    {
      src: "/images/event/event11.jpg",
      original: "/images/event/event11.jpg",
      width: 313,
      height: 320,
    },
  ],
};
